### ISSUE TITLE
Minimum of 1 Object Per Juggler

### ISSUE THREAD

**Issue by markadamdouglass** [prechac/prech.ac#4]
This issue seems to be related to: 

https://github.com/prechac/prech.ac/issues/3#issue-537859578

---

It seems to have a minimum of 1 object per juggler.

For example, when I put in:

http://prech.ac/4:11p00

The pattern does not come up.

The link that is developed is:

http://prechacthis.org/index.php?persons=4&objects=4or5or6or7or8or9or10or11or12or13or14or15or16or17or18or19or20&lengths=4&max=8&passesmin=1&passesmax=_&jugglerdoes=1%201p%200%200&exclude=&clubdoes=&react=&results=42

The key part being:

objects=4or5or6or7or8or9or10or11or12or13or14or15or16or17or18or19or20

Again, I had a little look in your code, but I do not fully understand Ruby.

In the file:

/lib/app.rb

I found:

```
def objects_string
    (number_of_people..(number_of_people * 5)).to_a.join('or')
  end
```

Could this start at 1 instead of `(number_of_people..`

Side Note: I still love this little tool. Very useful.

**Comment by amiel** [comment]
> Could this start at 1 instead of `(number_of_people..`

I think that would be fine.

**Comment by markadamdouglass** [comment]
Thank you for sorting this out @amiel. 

I’m impressed you sorted it so quickly. 

Thank you.
